### ISSUE TITLE
Integer overflow when running command

### ISSUE THREAD

**Issue by mrmanc** [repo-utils/org-labels#42]
I get the following error when trying to use this tool. I’m using macOS 12.0.1 on an Apple M1 Pro, using node v17.3.1.

<details>

```shell
 (node:91811) TimeoutOverflowWarning: 4294967296000 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:91811) TimeoutOverflowWarning: 4294967296000 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
Error: Not Found
    at BufferList.afterCreateAuthResponse [as _callback] (/Users/Mark.Crossfield/.nvm/versions/node/v17.3.1/lib/node_modules/org-labels/node_modules/ghauth/ghauth.js:39:19)
    at BufferList.end (/Users/Mark.Crossfield/.nvm/versions/node/v17.3.1/lib/node_modules/org-labels/node_modules/bl/bl.js:75:10)
    at Stream.onend (node:internal/streams/legacy:47:10)
    at Stream.emit (node:events:402:35)
    at Stream.handleEnd (/Users/Mark.Crossfield/.nvm/versions/node/v17.3.1/lib/node_modules/org-labels/node_modules/duplexer/index.js:81:21)
    at Stream.emit (node:events:402:35)
    at drain (/Users/Mark.Crossfield/.nvm/versions/node/v17.3.1/lib/node_modules/org-labels/node_modules/through/index.js:33:23)
    at Stream.stream.queue.stream.push (/Users/Mark.Crossfield/.nvm/versions/node/v17.3.1/lib/node_modules/org-labels/node_modules/through/index.js:41:5)
    at Stream.end (/Users/Mark.Crossfield/.nvm/versions/node/v17.3.1/lib/node_modules/org-labels/node_modules/through/index.js:17:35)
    at _end (/Users/Mark.Crossfield/.nvm/versions/node/v17.3.1/lib/node_modules/org-labels/node_modules/through/index.js:61:9)
    at Stream.stream.end (/Users/Mark.Crossfield/.nvm/versions/node/v17.3.1/lib/node_modules/org-labels/node_modules/through/index.js:70:5)
    at IncomingMessage.onend (node:internal/streams/readable:716:10)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

</details>

**Comment by Fishrock123** [comment]
I think this is a bug in one the libraries in the stack traces.

Also I am unsubscribing from this, feel free to fix it yourself if it's a bug in this module.

**Comment by mrmanc** [comment]
I’m not sure I would know where to start fixing it myself, or working out whether the bug is with this module or one of the libraries.

I’d happily raise an issue with one of the libraries if anyone could point which one is at fault. I’m guessing that you were unable to reproduce the problem yourself?
